sudo: required
services:
  - docker
git:
  depth: 1000
notifications:
  slack:
    secure: HEexFOE027rYqv8a4RkByDYo6gPggYyx4+R85RO92KR3PmcUEN0YzM7vk9HXV8eJc+8/xdDfIDqsK6R9NzT59Y80RivlaTiMjHpFb1EIAPKjRUfMpg6aGDUrztIbCx6+PdQn2irr0Yp8wbsXUr5xWFlsBuh0kw19GZmFdDqvikkIT81EsS8misf1xDsMcFQsNrTotwtfzGQAXlhUBKcocoif2a5y/nh/RaixcjROt6WXzOfWJ8jElJOTdJR4V0Zx/BLxBtbT0q9V1+jeliRCVURJWOe2atWtvnj6shtfe1n53Hat0wfv0AzQpXXpW1xYRg/nRZlzoqbivuNIpV4RfpBgrPxytgiTKIfR2A2qBSsg4RgMoQZkDTdVuGcXWA3O08LX4k02bZSa38HTMjzQ1xZ4qhZ77He5+Ik+NpvOMqnKcrGLalk6lv87BOQQrF0dvzZVIrHptkXRCiStCWt3x9qZeR4/BTtSzXzWiMZGFNICCjE+TbXgAJbnT7dgNIkc+33LIBPUwg2VVs+zZNuTJScu2BQahu/y1DR4GgKvSrCBPWSNSbcmH1ZCgTcTrirnCbc56neWd9oqVoIjjvFCPDl1zu/lJjpfmZEaahOI411wP4Ek8IftA6792sywqp10ZxVW3iN9/XGWGE37Udl6XOJpWLRiy1zWhojF2y5tq+Y=
  on_pull_requests: false
script:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u="$DOCKER_USERNAME" --password-stdin
deploy:
  - provider: script
    script:
      - make push_docker_image GIT_BRANCH="${NOTIFIER_BRANCH}" TAG_ALIAS="${NOTIFIER_BRANCH////-}"
    skip_cleanup: true
    on:
      all_branches: true
